apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
      - name: echo-server
        image: jmalloc/echo-server
        ports:
        - containerPort: 8080
